# Generated by Django 5.1 on 2026-07-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(help_text='e.g. T26-G-001', max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=50)),
                ('entry_day', models.DateField(choices=[('2026-07-23', 'Day 1 — July 23, 2026'), ('2026-07-24', 'Day 2 — July 24, 2026'), ('2026-07-25', 'Day 3 — July 25, 2026')])),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_by', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Entry Log',
                'verbose_name_plural': 'Entry Logs',
                'ordering': ['-scanned_at'],
                'unique_together': {('ticket_code', 'entry_day')},
            },
        ),
    ]
